# syntax=docker/dockerfile:1

FROM golang:1.20 AS builder

RUN go version

# ENV GOROOT /usr/local/bin

# Set destination for COPY
WORKDIR /build

# Download Go modules
COPY go.mod .
COPY go.sum .
RUN go mod download && go mod verify
COPY . .

# Copy the source code. Note the slash at the end, as explained in
# https://docs.docker.com/engine/reference/builder/#copy
COPY *.go ./

FROM docker:dind
RUN apk add --no-cache go
RUN go version

# Build
ENV CGO_ENABLED=0
ENV GOOS=linux
ENV GOARCH=amd64
ENV GO111MODULE=on
RUN go build -o ./bin/grpc_server .

# Optional:
# To bind to a TCP port, runtime parameters must be supplied to the docker command.
# But we can document in the Dockerfile what ports
# the application is going to listen on by default.
# https://docs.docker.com/engine/reference/builder/#expose
EXPOSE 9000

# Run
CMD ["./bin/grpc_server"]