name: Local Docker Compose Workflow

on:
  push:
    branches: [main] # Trigger on push to main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest # Use the latest Ubuntu runner

    steps:
      - uses: actions/checkout@v2 # Check out the repository code

      - name: Set up Docker
        uses: docker/setup-buildx-action@v1 # Sets up Docker Buildx (not strictly necessary for simple docker-compose up but useful for consistency)

      - name: Run Docker Compose
        run: |
          docker-compose up -d  # Start services in detached mode

      - name: Check Containers
        run: |
          docker-compose ps  # List containers to verify they're running
